
# ============================================================================
# CONFIGURATION: Set your Dropbox path here
# ============================================================================

# Dropbox path - CHANGE THIS to your actual path
DROPBOX_PAPER_PATH <- path.expand("~/Dropbox/Apps/Overleaf/pub_fin_schools")

# Check if Dropbox folder exists
if (!dir.exists(DROPBOX_PAPER_PATH)) {
  warning("Dropbox folder not found at: ", DROPBOX_PAPER_PATH)
  warning("Please create the folder or update DROPBOX_PAPER_PATH")
  # Create it if needed
  #dir.create(DROPBOX_PAPER_PATH, recursive = TRUE, showWarnings = FALSE)
}

# Create subdirectories in Dropbox if they don't exist
#dir.create(file.path(DROPBOX_PAPER_PATH, "tables"), showWarnings = FALSE, recursive = TRUE)
#dir.create(file.path(DROPBOX_PAPER_PATH, "figures"), showWarnings = FALSE, recursive = TRUE)

# Also create local output directories (for backup/version control)
dir.create(here("output/tex"), showWarnings = FALSE, recursive = TRUE)
dir.create(here("output/figures"), showWarnings = FALSE, recursive = TRUE)

# ============================================================================
# CACHE AND APPENDIX SETTINGS
# ============================================================================

cached_version <- FALSE  # Set to FALSE to rebuild everything

# Clear cache when rebuilding
if (!cached_version) {
  cache_files <- list.files("regressions_cache/", full.names = TRUE)
  if (length(cache_files) > 0) {
    file.remove(cache_files)
    cat("Cache cleared!\n")
  }
}

BUILDING_APPENDIX <- TRUE

# When using cached version, don't rebuild appendix
if(cached_version){
  BUILDING_APPENDIX <- FALSE
}

# Set cache option
knitr::opts_chunk$set(cache = cached_version)

# ============================================================================
# APPENDIX FILE INITIALIZATION
# ============================================================================

if(BUILDING_APPENDIX){
  # Initialize appendix in BOTH local and Dropbox
  appendix_header <- c(
    "% Auto-generated appendix",
    "% Regenerated from regressions.qmd",
    paste("% Last updated:", Sys.time()),
    "",
    "\\appendix",
    ""
  )
  
  # Write to local
  writeLines(appendix_header, here("output/tex", appendix_file))
  
  # Write to Dropbox - CHANGE THIS LINE
  writeLines(appendix_header, file.path(DROPBOX_PAPER_PATH, "si_docs", appendix_file))
  
  cat("Appendix initialized in:\n")
  cat("  - Local:", here("output/tex", appendix_file), "\n")
  cat("  - Dropbox:", file.path(DROPBOX_PAPER_PATH, "si_docs", appendix_file), "\n")
}

# ============================================================================
# HELPER FUNCTIONS FOR EXPORTING TO DROPBOX
# ============================================================================

# Function to export table to both local and Dropbox
export_table <- function(table_tex, filename) {
  # Write to local
  cat(table_tex, file = here("output/tex", filename))
  
  # Write to Dropbox
  cat(table_tex, file = file.path(DROPBOX_PAPER_PATH, "tables", filename))
  
  #cat("Exported table:", filename, "\n")
}

# Function to export figure to both local and Dropbox
export_figure <- function(plot_obj, filename, dpi = 300, width = 8, height = 8, beamer = FALSE) {
  
  if(beamer){
    filename <- paste0(
      tools::file_path_sans_ext(filename),
      "_beamer.pdf"
    )
  }
  # Save to local
  ggsave(
    here("output/figures", filename),
    plot = plot_obj,
    width = width,
    height = height,
    dpi = dpi)
  
  # Save to Dropbox
  ggsave(
    file.path(DROPBOX_PAPER_PATH, "figures", filename),
    plot = plot_obj,
    width = width,
    height = height,
    dpi = dpi)
  
  #cat("Exported figure:", filename, "\n")
}

# ============================================================================
# MODIFIED APPEND_TO_APPENDIX FUNCTION - EXPORTS TO DROPBOX
# ============================================================================

append_to_appendix <- function(title, description_lines, float_barrier = TRUE, label = NULL) {
  if (!BUILDING_APPENDIX) return(invisible(NULL))
  
  chunk_label <- knitr::opts_current$get("label")
  
  # Convert markdown title to LaTeX
  # "## Title" -> "\subsection{Title}"
  # "# Title" -> "\section{Title}"
  latex_title <- title
  if (grepl("^##\\s", title)) {
    latex_title <- gsub("^##\\s*(.+)$", "\\\\subsection{\\1}", title)
  } else if (grepl("^#\\s", title)) {
    latex_title <- gsub("^#\\s*(.+)$", "\\\\section{\\1}", title)
  }
  
  # Add label if provided
  if (!is.null(label)) {
    latex_title <- paste0(latex_title, "\n\\label{", label, "}")
  }
  
  lines <- c(
    "",
    latex_title,
    "",
    description_lines,
    "",
    paste0("% Content from chunk: ", chunk_label),  
    "% (Generated by regressions.qmd)",
    ""
  )
  
  if (float_barrier) {
    lines <- c(lines, "\\FloatBarrier", "")
  }
  
  # Append to local file
  write(lines, file = here("output/tex", appendix_file), append = TRUE)
  
  # Append to Dropbox file
  write(lines, file = file.path(DROPBOX_PAPER_PATH, "si_docs", appendix_file), append = TRUE)
}

# Alternative function: append table output directly to appendix
append_table_to_appendix <- function(table_tex, landscape = FALSE) {
  if (!BUILDING_APPENDIX) return(invisible(NULL))
  
  if(landscape){
    lines <- c("\\begin{landscape}", "", table_tex, "", "\\end{landscape}")
  }else{
    lines <- c("", table_tex, "")
  }
  
  # Append to local
  write(lines, file = here("output/tex", appendix_file), append = TRUE)
  
  # Append to Dropbox
  write(lines, file = file.path(DROPBOX_PAPER_PATH, "si_docs", appendix_file), append = TRUE)
}

# Add this to your setup chunk after the other helper functions

# ============================================================================
# APPEND FIGURE TO APPENDIX FUNCTION
# ============================================================================

append_figure_to_appendix <- function(plot_obj, filename, caption, label, width = "\\textwidth", fig_width = 8,            # Actual figure width in inches
                                      fig_height = 8, dpi = 300) {
  if (!BUILDING_APPENDIX) return(invisible(NULL))
  
  # Save figure to Dropbox
  fig_path <- file.path(DROPBOX_PAPER_PATH, "si_docs", filename)
  ggsave(fig_path, plot_obj, width = fig_width, height = fig_height)
  
  # Also save to local output folder (for backup)
  ggsave(here("output/figures", filename), plot_obj, width = fig_width, height = fig_height, dpi = dpi)
  
  # Add LaTeX code to appendix
  fig_latex <- c(
    "",
    "\\begin{figure}[htbp]",
    "  \\centering",
    paste0("  \\includegraphics[width=", width, "]{si_docs/", filename, "}"),
    #paste0("  \\caption{", caption, "}"),
    paste0("  \\label{", label, "}"),
    "\\end{figure}",
    "",
    "\\FloatBarrier",
    ""
  )
  
  append_table_to_appendix(paste(fig_latex, collapse = "\n"))
  
  cat("Appended figure to appendix:", filename, "\n")
}

# ============================================================================
# FINALIZE APPENDIX FUNCTION
# ============================================================================

finalize_appendix <- function() {
  if (!BUILDING_APPENDIX) return(invisible(NULL))
  
  lines <- c(
    "",
    "% End of auto-generated appendix",
    ""
  )
  
  # Write to local
  write(lines, file = here("output/tex", appendix_file), append = TRUE)
  
  # Write to Dropbox
  write(lines, file = file.path(DROPBOX_PAPER_PATH, "si_docs", appendix_file), append = TRUE)
  
  #cat("\n=== Appendix finalized ===\n")
  #cat("Local:", here("output/tex", appendix_file), "\n")
  #cat("Dropbox:", file.path(DROPBOX_PAPER_PATH, "si_docs", appendix_file), "\n")
}

# ============================================================================
# APPEND FILE TO APPENDIX FUNCTION
# ============================================================================

append_file_to_appendix <- function(filepath, float_barrier = FALSE, title = NULL) {
  if (!BUILDING_APPENDIX) return(invisible(NULL))
  
  # Check if file exists
  if (!file.exists(filepath)) {
    warning("File not found: ", filepath)
    return(invisible(NULL))
  }
  
  lines <- character()
  
  # Add title if provided
  if (!is.null(title)) {
    # Convert markdown title to LaTeX
    latex_title <- title
    if (grepl("^##\\s", title)) {
      latex_title <- gsub("^##\\s*(.+)$", "\\\\subsection{\\1}", title)
    } else if (grepl("^#\\s", title)) {
      latex_title <- gsub("^#\\s*(.+)$", "\\\\section{\\1}", title)
    }
    lines <- c(lines, "", latex_title, "")
  }
  
  # Read the file content
  file_content <- readLines(filepath, warn = FALSE)
  lines <- c(lines, "", file_content, "")
  
  # Add float barrier if requested
  if (float_barrier) {
    lines <- c(lines, "", "\\FloatBarrier", "")
  }
  
  # Append to local appendix
  write(lines, file = here("output/tex", appendix_file), append = TRUE)
  
  # Append to Dropbox appendix
  write(lines, file = file.path(DROPBOX_PAPER_PATH, "si_docs", appendix_file), append = TRUE)
  
  cat("Appended file to appendix:", filepath, "\n")
  if (!is.null(title)) cat("  with title:", title, "\n")
}
